# golangci-lint configuration for hioload-ws
# Author: momentics <momentics@gmail.com>
# License: Apache-2.0

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - tests/fake
  skip-files:
    - ".*_test\\.go$"

linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
  disable-all: false
  fast: true

linters-settings:
  golint:
    min-confidence: 0.8
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    check-shadowing: true
  staticcheck:
    checks: ["all"]

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0