run:
  timeout: 5m
  build-tags:
    - "linux"
    - "cgo"

linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - misspell
    - unused

issues:
  exclude-rules:
    - path: internal/concurrency/affinity_linux.go
      text: "could not determine kind of name for C."
