name: Build & Test Examples (Linux & Windows)

on:
  push:
    branches: [main, develop]
  pull_request:

env:
  GO_VERSION: "1.23"
  GOEXPERIMENT: aliastypeparams
  CGO_ENABLED: "0"
  GO111MODULE: "on"

jobs:
  build-and-test:
    name: Build Examples and Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    env:
      CGO_ENABLED: "0"
      GOEXPERIMENT: aliastypeparams
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install libnuma-dev on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libnuma-dev

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Download dependencies
        run: |
          go mod tidy

      - name: Run library tests
        run: |
          go test ./... -v -timeout 10m

      - name: Build all examples
        shell: bash
        working-directory: ./examples
        run: |
          mkdir -p ../../dist/examples/${{ matrix.os }}
          for dir in */; do
            if [ -f "$dir/main.go" ]; then
              echo "Building example: $dir on ${{ matrix.os }}"
              if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
                CGO_ENABLED=0 GOOS=windows GOEXPERIMENT=aliastypeparams \
                  go build -o "../../dist/examples/${{ matrix.os }}/${dir%/}.exe" "./$dir"
              else
                CGO_ENABLED=0 GOOS=linux GOEXPERIMENT=aliastypeparams \
                  go build -o "../../dist/examples/${{ matrix.os }}/${dir%/}" "./$dir"
              fi
            fi
          done

      - name: Upload example binaries
        uses: actions/upload-artifact@v4
        with:
          name: example-binaries-${{ matrix.os }}
          path: dist/examples/${{ matrix.os }}/
