# File: .github/workflows/build-examples.yml
# Name: Build Examples (Windows Only)
# Author: momentics <momentics@gmail.com>
# License: Apache-.0

name: Build Examples (Windows Only)

on:
  push:
    branches: [main, develop]
  pull_request:

env:
  GO_VERSION: "1.23"
  GOEXPERIMENT: aliastypeparams
  CGO_ENABLED: "1"
  GO111MODULE: "on"

jobs:
  build-examples-windows:
    name: Build Examples on Windows
    runs-on: windows-latest
    env:
      CGO_ENABLED: "1"
      GOEXPERIMENT: aliastypeparams
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build all examples
        shell: bash
        working-directory: ./examples
        run: |
          mkdir -p ../../dist/examples/windows-latest
          for dir in */; do
            if [ -f "$dir/main.go" ]; then
              echo "Building example: $dir on Windows"
              CGO_ENABLED=1 GOOS=windows GOEXPERIMENT=aliastypeparams \
                go build -o "../../dist/examples/windows-latest/${dir%/}.exe" "./$dir"
            fi
          done

      - name: Upload example binaries
        uses: actions/upload-artifact@v4
        with:
          name: example-binaries-windows
          path: dist/examples/windows-latest/
