# File: .github/workflows/build-examples.yml
# Name: Build Examples (Linux & Windows)
# Author: momentics <momentics@gmail.com>
# License: Apache-2.0
#
# This workflow builds all example programs on both Linux and Windows
# with Go 1.23 (+ GOEXPERIMENT=aliastypeparams and CGO_ENABLED=1).
# Shell for commands set explicitly to bash for correct execution on Windows.

name: Build Examples (Linux & Windows)

on:
  push:
    branches: [main, develop]
  pull_request:

env:
  GO_VERSION: "1.23"
  GOEXPERIMENT: aliastypeparams
  CGO_ENABLED: "1"
  GO111MODULE: "on"

jobs:
  build-examples:
    name: Build Examples
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    env:
      GOEXPERIMENT: aliastypeparams
      CGO_ENABLED: "1"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libnuma-dev

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build all examples
        shell: bash
        working-directory: ./examples
        run: |
          mkdir -p ../../dist/examples/${{ matrix.os }}
          for dir in */; do
            if [ -f "$dir/main.go" ]; then
              echo "Building example: $dir on ${{ matrix.os }}"
              if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
                CGO_ENABLED=1 GOOS=windows GOEXPERIMENT=aliastypeparams go build -o "../../dist/examples/${{ matrix.os }}/${dir%/}.exe" "./$dir"
              else
                CGO_ENABLED=1 GOOS=linux GOEXPERIMENT=aliastypeparams go build -o "../../dist/examples/${{ matrix.os }}/${dir%/}" "./$dir"
              fi
            fi
          done

      - name: Upload example binaries
        uses: actions/upload-artifact@v4
        with:
          name: example-binaries-${{ matrix.os }}
          path: dist/examples/${{ matrix.os }}/
