# File: .github/workflows/lint-build-examples.yml
# Name: Lint & Build Examples (Linux & Windows)
# Author: momentics <momentics@gmail.com>
# License: Apache-2.0

name: Lint & Build Examples (Linux & Windows)

on:
  push:
    branches: [main, develop]
  pull_request:

env:
  GO_VERSION: "1.23"
  GOEXPERIMENT: aliastypeparams
  CGO_ENABLED: "1"            # Enable Cgo for static analysis
  GO111MODULE: "on"

jobs:
  lint:
    name: Static Analysis
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: "1"
      GOEXPERIMENT: aliastypeparams
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create golangci-lint config
        run: |
          cat > .golangci.yml << 'EOF'
          run:
            timeout: 5m
            build-tags:
              - "linux"
              - "cgo"
          linters:
            enable:
              - gofmt
              - govet
              - staticcheck
              - errcheck
              - ineffassign
              - misspell
              - unused
          issues:
            exclude-rules:
              - path: internal/concurrency/affinity_linux.go
                text: "could not determine kind of name for C."
          EOF

      - name: Install libnuma-dev
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libnuma-dev

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.59
          config: .golangci.yml

  build-examples:
    name: Build Examples
    runs-on: ${{ matrix.os }}
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    env:
      CGO_ENABLED: "1"
      GOEXPERIMENT: aliastypeparams
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build all examples
        working-directory: ./examples
        run: |
          mkdir -p ../../dist/examples/${{ matrix.os }}
          for dir in */; do
            if [ -f "$dir/main.go" ]; then
              echo "Building example: $dir on ${{ matrix.os }}"
              if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
                GOOS=windows CGO_ENABLED=1 GOEXPERIMENT=aliastypeparams go build -o "../../dist/examples/${{ matrix.os }}/${dir%/}.exe" "./$dir"
              else
                GOOS=linux   CGO_ENABLED=1 GOEXPERIMENT=aliastypeparams go build -o "../../dist/examples/${{ matrix.os }}/${dir%/}"   "./$dir"
              fi
            fi
          done

      - name: Upload example binaries
        uses: actions/upload-artifact@v4
        with:
          name: example-binaries-${{ matrix.os }}
          path: dist/examples/${{ matrix.os }}/
