# File: .github/workflows/release.yml
# Workflow для публикации релизов hioload-ws через GoReleaser
#
# Author: momentics <momentics@gmail.com>
# License: Apache-2.0

name: Release

on:
  push:
    tags:
      - 'v*.*.*'   # семантические теги вида v1.2.3

permissions:
  contents: write   # требуется для создания Release
  packages: write   # если публикуются пакеты

jobs:
  release:
    name: Publish Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          check-latest: true

      - name: Install GoReleaser
        # Исправлено: правильный путь к Action
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest

      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Создать GitHub Release, собрать артефакты и опубликовать
          goreleaser release --rm-dist

      - name: Trigger pkg.go.dev re-index
        run: |
          for i in {1..3}; do
            curl -s -o /dev/null "https://pkg.go.dev/github.com/momentics/hioload-ws?tab=doc" && break
            sleep 10
          done

      - name: Verify pkg.go.dev indexing
        run: |
          echo "Проверьте https://pkg.go.dev/github.com/momentics/hioload-ws для обновленной документации."
