# File: .github/workflows/release.yml
# This workflow publishes tagged releases of hioload-ws using GoReleaser,
# which in turn generates GitHub releases, Docker images (if configured),
# and drives pkg.go.dev documentation updates.
#
# Author: momentics <momentics@gmail.com>
# License: Apache-2.0

name: Release

on:
  push:
    tags:
      - 'v*.*.*'   # Trigger on semantic version tags like v1.2.3

jobs:
  release:
    name: Publish Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          check-latest: true

      - name: Install GoReleaser
        uses: goreleaser/action@v2
        with:
          version: latest
          install: true

      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create GitHub release, build archives, and push artifacts.
          goreleaser release --rm-dist

      - name: Trigger pkg.go.dev re-index
        # Ping pkg.go.dev to ensure the new version is indexed immediately
        run: |
          for i in {1..3}; do
            curl -s -o /dev/null "https://pkg.go.dev/github.com/momentics/hioload-ws?tab=doc" && break
            sleep 10
          done

      - name: Verify pkg.go.dev indexing
        run: |
          echo "Check https://pkg.go.dev/github.com/momentics/hioload-ws for updated documentation."
