name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Publish Release
    runs-on: ubuntu-latest

    steps:
      - name: Trigger pkg.go.dev re-index
        run: |
          for i in {1..3}; do
            curl -s -o /dev/null "https://pkg.go.dev/github.com/momentics/hioload-ws?tab=doc" && break
            sleep 10
          done

      - name: Verify pkg.go.dev indexing
        run: |
          echo "Check https://pkg.go.dev/github.com/momentics/hioload-ws for updated documentation."
